### ISSUE TITLE
Occasional issue when shutting down plexi

### ISSUE THREAD

**Issue by collectioncard** [Team-Creative-Name/Plexi#18]
Seemingly randomly, Plexi is unable to shut down properly. Following is the error printed to the log:

```
279525 [JDA Gateway-Worker 1] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Was unable to schedule next packet due to rejected execution by threadpool
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@43e66292 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4d21949e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 8]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
    at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
    at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
    at net.dv8tion.jda.internal.requests.WebSocketSendingThread.scheduleIdle(WebSocketSendingThread.java:82)
    at net.dv8tion.jda.internal.requests.WebSocketSendingThread.scheduleNext(WebSocketSendingThread.java:167)
    at net.dv8tion.jda.internal.requests.WebSocketSendingThread.run(WebSocketSendingThread.java:157)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
Even though this exception is thrown, the bot doesnt seem to have an issue shutting down.

**Comment by collectioncard** [comment]
Possibly fixed in commit 5ba9e1f

**Comment by collectioncard** [comment]
*sigh* I got it the second I stopped the bot. Of course it didn't show any of the times I tested it. This bug is not fixed.

**Comment by collectioncard** [comment]
Update: Talked to a dev of JDA and they said that it is not something to be worried about. This is going to be marked as wontfix and closed.
